### ISSUE TITLE
Wrapper support for Seaborn

### ISSUE THREAD

**Issue by nowozin** [stevengj/PyPlot.jl#116]
[Seaborn](http://stanford.edu/~mwaskom/software/seaborn/index.html) is a library based on matplotlib which simplifies common statistical plots.  It would be great to have a first class Julia interface to this library.

**Comment by nowozin** [comment]
[Seaborn](http://stanford.edu/~mwaskom/software/seaborn/index.html) is a library based on matplotlib which simplifies common statistical plots.  It would be great to have a first class Julia interface to this library.

**Comment by stevengj** [comment]
Note that you can call Seaborn already by using PyPlot and PyCall, as [discussed on the mailing list](https://groups.google.com/d/msg/julia-users/dp_MIs-WucE/_TsOsI0y1doJ).  If you wanted a higher-level Julia wrapper, that would probably belong in a separate package (depending on PyPlot).

(The main reason for the PyPlot package, rather than calling Matplotlib directly via PyCall, is to support interactive GUI backends, which require an event loop, and to support inline IJulia plots.   However, `using PyCall, PyPlot; @pyimport seaborn as sns` already gives you this, since Seaborn relies on the Matplotlib backend.)

**Comment by nowozin** [comment]
Thanks Steven, the mailing list link is very helpful, I close this issue.
