### ISSUE TITLE
AttributeError: tuple' object has no attribute 'autoscale_None'"

### ISSUE THREAD

**Issue by vollmersj** [stevengj/PyPlot.jl#142]
I tried to have histogram that has the same scale in two plots. Porting different Python examples resulted in the same error
ERROR: PyError (:PyObject_Call) <type 'exceptions.AttributeError'>
AttributeError("'tuple' object has no attribute 'autoscale_None'",).

Any help or resolution is greatly appreciated.
```
PyPlot.clf()
(fig,axes)=PyPlot.subplots(2,1)
@pyimport mpl_toolkits.axes_grid1 as axgrid

im=axes[1][:hist2d](x,y,100)                  
im=axes[2][:hist2d](x2,y2,100)              

ax = gca()              
divider = axgrid.make_axes_locatable(ax)
cax = divider[:append_axes]("right", size="5%", pad=0.05)
colorbar(im, cax=cax)

ERROR: PyError (:PyObject_Call) <type 'exceptions.AttributeError'>
AttributeError("'tuple' object has no attribute 'autoscale_None'",)
```

**Comment by stevengj** [comment]
According to the [hist2d documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.hist2d), it returns a tuple `(counts, xedges, yedges, Image)`.  According to the [colorbar documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.colorbar), the first argument should be "the `Image`, `ContourSet`, etc. to which the colorbar applies".

So, `colorbar(im, cax=cax)` is wrong because you are passing a tuple as the first argument, when you should be just passing the `Image` (which is the fourth component of the tuple).    If I change it to `colorbar(im[4], cax=cax)`, to pass the `Image`, it works for me.

(I don't understand how the corresponding code could have worked in Python, either.)

**Comment by riteshporwal** [comment]
> According to the [hist2d documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.hist2d), it returns a tuple `(counts, xedges, yedges, Image)`. According to the [colorbar documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.colorbar), the first argument should be "the `Image`, `ContourSet`, etc. to which the colorbar applies".
> 
> So, `colorbar(im, cax=cax)` is wrong because you are passing a tuple as the first argument, when you should be just passing the `Image` (which is the fourth component of the tuple). If I change it to `colorbar(im[4], cax=cax)`, to pass the `Image`, it works for me.
> 
> (I don't understand how the corresponding code could have worked in Python, either.)

To pass 4th element of the tuple (here it is a plot image) one must do im[3] not im[4].
