### ISSUE TITLE
Taking full advantage of static compilation

### ISSUE THREAD

**Issue by malmaud** [stevengj/PyPlot.jl#143]
Now that we have static compliation (https://github.com/JuliaLang/julia/pull/8745#issuecomment-122398077), running `Base.compile(:PyPlot)` does result in a significant speedup in `using PyPlot`, but there is still a latency of ~5 seconds. I wonder if we could judiciously insert some `Base.precompile` statements into `PyPlot.jl` to bring the latency closer to 0.

**Comment by stevengj** [comment]
Is the latency in PyPlot, or is it in PyCall?

**Comment by stevengj** [comment]
For me, after precompiling, it still takes about 10 seconds.   A little over half of that time seems to be in `pyinitialize()` from PyCall.

**Comment by malmaud** [comment]
I'm getting similar timings.

**Comment by stevengj** [comment]
Adding `precompile(pyinitialize, ())` to PyCall shaves off a couple of seconds.

**Comment by stevengj** [comment]
If I add `pyinitialize()` at the end of PyCall.jl, then the time for `using PyCall; pyinitialize()` goes down from   6.8 seconds to 0.37 seconds, and the time for PyPlot.jl goes down to 1.1 seconds, so it seems that this is almost entirely a PyCall issue.

The biggest problem with putting `pyinitialize()` in PyCall.jl is that I'm not sure if the resulting `PyCall.ji` compiled file will then work with other versions of Python, because I'm afraid that some runtime constants are getting hard-coded ... I'm not exactly sure what is safe here.

**Comment by stevengj** [comment]
Closing in favor of stevengj/PyCall.jl#167 since this seems to be almost entirely a PyCall issue.

**Comment by stevengj** [comment]
Reopening.  With the latest PyCall, `using PyCall` takes 1.26 seconds for me after compiling, while `using PyPlot` takes 4.8 seconds (vs. 12.1 seconds before compiling).  We should be able to shave this down some more.

**Comment by stevengj** [comment]
Also `Base.compile(:PyPlot)` gives a `sh: sysctl: command not found` warning; not sure what that is about.  (`sysctl` is in `/usr/sbin`).

**Comment by stevengj** [comment]
Okay, the time to load seems to break down as follows:
![image](https://cloud.githubusercontent.com/assets/2913679/8856168/12bba5ce-3137-11e5-8c17-af2710bd926e.png)
The biggest times are taken by:
* `find_backend`: 1.72 seconds
* importing PyCall: 1.26 seconds
* Mystery things, not part of `__init__`: 0.56 seconds — possibly importing other modules?
* loading `pyplot` etc: 0.51 seconds — almost all of this is in calling `pywrap` (0.45 seconds)
* `init_pyplot_funcs`: 0.44 seconds

**Comment by stevengj** [comment]
In `find_backend`, most of the time (1.2 seconds) is spent in Python, loading the backend module.  Nothing we can do about that.

**Comment by stevengj** [comment]
Once we have dot overloading, I could get rid of the `pywrap` entirely.   I could also just get rid of it now, and tell people to use `foo(...)` or `PyPlot.foo` rather than `plt.foo()`.  It's a little silly to support both styles.

**Comment by stevengj** [comment]
I have a draft implementation (not pushed yet) that eliminates all of the `addhelp` calls on 0.4 by switching over to the new `@doc` system, and at the same time fetching the docstrings lazily from Python rather than at load time.  This reduces the load time to 3.9 seconds after compilation.  Progress!

Unfortunately, this is where I ran into JuliaLang/julia#12284: my docstring access is lost upon compilation.

**Comment by stevengj** [comment]
Okay, now that a fix for 12284 is pending, I've pushed ddaa060478d511de6b460f324851e93551f2a97d to use the new documentation system (if available) to speed up load times further.

**Comment by stevengj** [comment]
Closing this as I'm using precompilation as much as seems reasonably possible right now.
