### ISSUE TITLE
methods() does not return functions associated with a type

### ISSUE THREAD

**Issue by kubaroth** [stevengj/PyPlot.jl#176]
Compared to the results run on based types this one produces an array
>f = figure()
> methods(f)
0-element Array{Any,1}

I was expecting to see a list of function which take the figure as a parameter. 

Perhaps this is the expected behaviour since the module wraps python object and probably Julia has no idea about underlying python structure.

Is there anything here which can be improved? It is very hard to find out what can be done to the figure (object) without going through the docs or knowing pyplot very well.

Thank you

**Comment by stevengj** [comment]
When in doubt, you can do it the way you would in Python, where you would use the `inspect` module:
```jl
using PyCall, PyPlot
f = figure()
pyimport("inspect")[:getmembers](f)
```
The Julia `methods` function is totally the wrong place for this, since `methods(function)` returns the methods defined for a given `function`.   You could do `methodswith(typeof(f))`, but this returns the *Julia* functions that take an argument of that type, not the Python members.

In any case, you don't really pass figures to functions; that's not how the Matplotlib API works.  There's really no substitute for reading documentation.

(The downside of PyPlot and PyCall is that in order to use it effectively, you need to know *both* Python and Julia.  You need to know Python to read the Matplotlib documentation, and you need to know Julia in order to translate the documentation to Julia following PyCall's rules.)
