### ISSUE TITLE
Undefined symbol: FcWeightFromOpenType

### ISSUE THREAD

**Issue by thomascello** [stevengj/PyPlot.jl#220]
Hi, I'm really sorry to bother you again. This will be my last time!

On a other computer I have an issue with PyPlot. 

`julia> using PyCall
julia> pygui(:qt)
:qt
julia> using PyPlot
julia> a = [1,2]
2-element Array{Int64,1}:
 1
 2
julia> plot(a,a)
julia: symbol lookup error: /usr/bin/../lib/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenType
`

When I'm doing  `ENV["MPLBACKEND"] = "Agg"`, as proposed in this [issue 266](https://github.com/tbreloff/Plots.jl/issues/266),  it works but so image is shown even with `pygui(true)` or `show()`.

Can you help on this last one? 

Thanks you so much.

**Comment by stevengj** [comment]
That error is a problem with on the Python side: see  `ContinuumIO/anaconda-issues#368`

The `Agg` backend is an image-only backend; it allows you to save images with `savefig`, and can display them in IJulia, but can't open GUI windows.

Why are you forcing the Qt backend, rather than let PyPlot pick its own backend?  Have you tried another backend, e.g. the Tk backend? 

In general, if you are not comfortable dealing with Python installation issues, I recommend using Conda [as described here](https://github.com/stevengj/PyCall.jl#automating-python-installation).

**Comment by thomascello** [comment]
Thanks a lot for your answer. 
I already saw `ContinuumIO/anaconda-issues#368` but I don't have conda and by doing:
`[tm@tm ~]$ pip install --user asmeurer pango` 
I got:
`Collecting asmeurer
Could not find a version that satisfies the requirement asmeurer (from versions: )
No matching distribution found for asmeurer
`
I also already did:
`ENV["PYTHON"]=""
Pkg.build("PyCall")
using PyPlot`
But I still have the same problem.

I was forcing  the Qt backend because it was proposed on issue 266 :) but indeed I should not do that. I just did `ENV["MPLBACKEND"] = "Tk"` and it works now. I think that my backend is set to the wrong backend since the start ...

Thank you so much! Sorry for these silly questions.

**Comment by thomascello** [comment]
I just restarted julia and it's doing the same error again. How can I set `ENV["MPLBACKEND"] = "Tk"` as default?

**Comment by stevengj** [comment]
You can set the backend (to `TkAgg`) in your [matplotlibrc file](http://matplotlib.org/users/customizing.html).

However, if you do nothing (i.e. just do `using PyPlot`), then `tkagg` is already the default backend.  Does just doing `using PyPlot` work for you?  If not, maybe you already have a matplotlibrc file that is setting a different default backend?

**Comment by thomascello** [comment]
Thanks! 

When I'm just doing `using PyPlot` it is not working, I get the initial error `symbol lookup error: /usr/bin/../lib/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenType.`. 
I took a look at the matplotlibrc and the default backend is `qt5agg`.
But when I set it to `tkagg` and then try again I get this:

`julia> import PyPlot
julia> a = [1,2]
julia> plot(a,a)
ERROR: UndefVarError: plot not defined
` 

Do you understand why? 

Thanks again

**Comment by stevengj** [comment]
The `FcWeightFromOpenType` error is because your matplotlibrc file was specifying the Qt backend, but your Qt libraries are not installed correctly.

You need `using PyPlot` (not `import PyPlot`) if you want it to export the `plot` command.  (This is somewhat analogous to `from pyplot import *` in Python.)  If you do `import PyPlot`, the module is loaded but no other symbols are imported, so you'd need `PyPlot.plot`.

**Comment by thomascello** [comment]
Sorry for that, the error is still there even if I do the same with `using PyPlot`... 
I just realized that I'm not using the Matplotlib from Python but the one from Julia right? 
I looking the location of the matplotlibrc file of Julia to make the same change to be sure that Julia is using this specific matplotlibrc...

Thanks

**Comment by stevengj** [comment]
If you type `using PyPlot`, is there an error message?

You are calling the Python Matplotlib from Julia.    Which Python you are using depends on your PyCall configuration.

You can find out the correct Matplotlib filename by
```jl
using PyCall
pyimport("matplotlib")["matplotlib_fname"]()
```

**Comment by thomascello** [comment]
Thank you so much! 

This was exactly the command line I was looking for. Now it works perfectly with the right backend set as default

Thanks again, have a great day.
