### ISSUE TITLE
Non-interactive mode

### ISSUE THREAD

**Issue by ihnorton** [stevengj/PyPlot.jl#41]
A [StackOverflow question](http://stackoverflow.com/questions/22041461/julia-pyplot-from-scrip-not-interactive) today raised the issue that if PyPlot is run from a script, the plot is never displayed: the plot call returns, and Julia immediately exits.

One thought I had was to override `show(::Figure)` and block there pending user input, but ideally only the final plot in the script should block.

**Comment by bjarthur** [comment]
```@pyimport matplotlib.pyplot as plt``` to get non-interactive mode is quite useful for batch processing of data.  would be great to have this documented.  what "niceties" of PyPlot are lost by doing this?

**Comment by stevengj** [comment]
@bjarthur, you lose the more Julian style of just typing `plot` (or `PyPlot.plot`) rather than having to qualify everything with `plt.`, the LaTeXStrings import, the colormap conversions, some improved consistency of array-dimensionality handling, etc.

It should be straightforward to modify PyPlot to check the `isinteractive()` function to see if Julia is running in non-interactive mode, and if not then to initialize the pyplot module in non-interactive mode (skipping all of the GUI event-loop stuff), if anyone wants to take a crack at it.
