### ISSUE TITLE
No errors but no plot window shows up

### ISSUE THREAD

**Issue by pwl** [stevengj/PyPlot.jl#59]
I have been using PyPlot for a few days now and it worked flawlessly until yesterday, when the package stopped producing plots.  I have no idea why this happened as I don't recall me making any updates etc.   The example from README, when I input it in the REPL, results in the following output (there are no errors), but no window pops up.

```
julia> using PyPlot

julia> x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x));

julia> plot(x, y, color="red", linewidth=2.0, linestyle="--")
1-element Array{Any,1}:
 PyObject <matplotlib.lines.Line2D object at 0x7f7882c8feb8>

julia> title("A sinusoidally modulated sinusoid")
PyObject <matplotlib.text.Text object at 0x7f7882cde198>

```

I am using Archlinux, Julia Version 0.3.0-prerelease+2954 and PyPlot from master.

**Comment by SHWB** [comment]
Hello, I'm writing here because I'm not sure whether to open a new issue ticket.

I am on an Ubuntu 14.04 machine, with Julia 0.3.5. I'm going to illustrate the behavior using the example from the README. 

```julia
    using PyPlot
    x = linspace(0,2*pi,1000); y = sin(3*x + 4*cos(2*x));
    plot(x, y, color="red", linewidth=2.0, linestyle="--")
    title("A sinusoidally modulated sinusoid")
```

1. This produces no output if the above code is a script I run in the system terminal. In this case, the output of `pygui()` is `tk`, and the outcome doesn't change for any backend I manually force. 

2. If I run the same code inside the REPL, it works flawlessly. Even if I include the script file.

3. The code 
```julia
using PyCall
@pyimport numpy
@pyimport pylab
x = linspace(0,2pi,1000); y = sin(3x + 4cos(2x));
pylab.plot(x, y; color="red", linewidth=2.0, linestyle="--")
pylab.show()
```
works if called as a script in the system shell and in the REPL as well.

I am honestly quite new to Julia and I couldn't say if this problem is related to PyPlot.jl or Julia itself.

**Comment by stevengj** [comment]
@SHWB, if you run in a script, then I think Matplotlib defaults to running non-interactively, and PyCall does the same.  Try explicitly running `plt.show()`.

In any case, your problem is unrelated to the problem of the original poster, which seems to have been a backend issue, so I'm closing this particular issue.

**Comment by prajval10** [comment]
I have the same issue as @pwl. I'm working on `Ubuntu 18.04` and `Julia v1.0`. I've tried `plt.show()` after using `plot(..)` as well but it doesn't show the required plot.
